#!/bin/sh - 

fname=1.h5


rm $fname

size=1000

./dbase -dbase $fname -new 

for i in 1 2 3 4 5 6 7 8 9 10; do
    ./dbase -dbase $fname  -add -group $i -signal foo1 -testsig $size
    ./dbase -dbase $fname  -add -group $i -signal foo2 -testsig $size
    ./dbase -dbase $fname  -add -group $i -signal foo3 -testsig $size
    ./dbase -dbase $fname  -add -group $i -signal foo4 -testsig $size 
done



